version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /.*
  script: guestbook.application
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]
