application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: 2.0.2
