runtime: python27
api_version: 1
threadsafe: true
default_expiration: "0"

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js
  http_headers:
    Isolated-Script: "true"

- url: /tasks/.*
  script: guestbook.app
  login: admin

- url: /.*
  script: guestbook.app

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
